# Generated by Django 6.1.1 on 2026-09-16 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_support_active', models.BooleanField(default=True)),
                ('assigned_mentor', models.CharField(default='Teacher Mercy (Senior CBC Facilitator)', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
                ('term_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.termpackage')),
            ],
            options={
                'unique_together': {('student', 'term_package')},
            },
        ),
        migrations.CreateModel(
            name='DailyLessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(auto_now=True)),
                ('comprehension_stars', models.PositiveSmallIntegerField(default=5)),
                ('notes', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.dailylessonguide')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('photo_url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('local_materials_used', models.CharField(default='Plastic bottle, charcoal, fine sand, cotton', max_length=255)),
                ('rubric_score', models.CharField(choices=[('EE', 'Exceeding Expectations (Level 4)'), ('ME', 'Meeting Expectations (Level 3)'), ('AE', 'Approaching Expectations (Level 2)'), ('BE', 'Below Expectations (Level 1)')], default='EE', max_length=5)),
                ('mentor_feedback', models.TextField(blank=True, default='Outstanding initiative! The filtration layers were cleanly separated and clear water was achieved.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tracker.enrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.dailylessonguide')),
            ],
        ),
    ]
