# Generated by Django 6.1.1 on 2026-09-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('estate', models.CharField(max_length=100)),
                ('host_parent', models.CharField(default='Mama Liam', max_length=100)),
                ('curriculum_code', models.CharField(default='CBC', max_length=20)),
                ('grade_target', models.CharField(default='Grade 4', max_length=50)),
                ('max_children', models.PositiveSmallIntegerField(default=6)),
                ('current_enrolled', models.PositiveSmallIntegerField(default=4)),
                ('meeting_days', models.CharField(default='Mon, Wed, Fri (09:00 AM - 01:00 PM)', max_length=150)),
                ('monthly_share_kes', models.DecimalField(decimal_places=2, default=4500.0, max_digits=8)),
                ('description', models.TextField()),
                ('focus_areas', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Certified CBC & Cambridge Educator', max_length=150)),
                ('bio', models.TextField()),
                ('avatar_url', models.CharField(max_length=255)),
                ('curriculum_specialty', models.JSONField(default=list)),
                ('subjects', models.JSONField(default=list)),
                ('hourly_rate_kes', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, default=4.95, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=28)),
                ('has_police_clearance', models.BooleanField(default=True)),
                ('has_tsc_accreditation', models.BooleanField(default=True)),
                ('estates_covered', models.JSONField(default=list)),
                ('phone_contact', models.CharField(default='+254700123456', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
