# Generated by Django 6.1.1 on 2026-09-16 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=50)),
                ('term', models.PositiveSmallIntegerField(default=1)),
                ('academic_year', models.PositiveIntegerField(default=2026)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('price_kes', models.DecimalField(decimal_places=2, default=6500.0, max_digits=10)),
                ('badge', models.CharField(default='Complete Homeschool-in-a-Box', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=list)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='curriculum.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='WeekModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('theme_title', models.CharField(max_length=150)),
                ('learning_outcomes', models.JSONField(default=list)),
                ('printable_pack_title', models.CharField(default='Week Consolidated Printable Pack (PDF)', max_length=150)),
                ('page_count', models.PositiveSmallIntegerField(default=12)),
                ('term_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='curriculum.termpackage')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLessonGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('subject', models.CharField(max_length=100)),
                ('time_slot', models.CharField(default='08:30 AM - 09:15 AM', max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=35)),
                ('topic', models.CharField(max_length=150)),
                ('parent_script', models.TextField(help_text='Exact script the parent reads aloud to the child')),
                ('learning_objective', models.TextField()),
                ('local_materials', models.JSONField(default=list, help_text='List of everyday items, e.g. jiko charcoal, plastic bottle')),
                ('step_by_step_activity', models.TextField()),
                ('worksheet_name', models.CharField(default='Worksheet #1 (Fractions & Shapes)', max_length=150)),
                ('is_lab_practical', models.BooleanField(default=False)),
                ('has_photo_submission', models.BooleanField(default=False)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.weekmodule')),
            ],
            options={
                'ordering': ['day_number', 'id'],
            },
        ),
    ]
