# Generated by Django 6.1.1 on 2026-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_handle', models.CharField(max_length=100)),
                ('parent_name', models.CharField(blank=True, max_length=150)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('template_id', models.CharField(blank=True, max_length=50)),
                ('commission_kes', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8)),
                ('status', models.CharField(default='Credited', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=50, unique=True)),
                ('creator_name', models.CharField(max_length=150)),
                ('creator_handle', models.CharField(max_length=100)),
                ('social_platform', models.CharField(default='TikTok & Instagram', max_length=100)),
                ('creator_avatar', models.CharField(blank=True, max_length=255)),
                ('creator_bio', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('curriculum_code', models.CharField(default='CBC', max_length=50)),
                ('grade_level', models.CharField(default='Grade 4', max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('sample_week_theme', models.CharField(blank=True, max_length=200)),
                ('highlights', models.JSONField(default=list)),
                ('sample_lessons', models.JSONField(default=list)),
                ('imports_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('affiliate_commission_kes', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(default='Global Open Curriculum Initiative', max_length=150)),
                ('version', models.CharField(default='2026.1', max_length=20)),
                ('schema_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(default='mercy', max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('slot_type', models.CharField(default='pod', max_length=30)),
                ('target_group', models.CharField(default='Estate Pod', max_length=150)),
                ('max_learners', models.PositiveSmallIntegerField(default=6)),
                ('booked_learners', models.PositiveSmallIntegerField(default=0)),
                ('hourly_rate_kes', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8)),
                ('status', models.CharField(default='Available', max_length=30)),
                ('location', models.CharField(default='Physical Pod & Virtual', max_length=150)),
                ('live_link', models.CharField(default='https://meet.jit.si/somahome-live', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='dailylessonguide',
            name='local_materials',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dailylessonguide',
            name='worksheet_name',
            field=models.CharField(default='Worksheet #1', max_length=150),
        ),
    ]
