# Generated by Django 6.1.1 on 2026-09-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('CREATOR', 'Creator'), ('ADMIN', 'Admin')], default='PARENT', max_length=20),
        ),
    ]
