# Generated by Django 5.0.14 on 2026-09-28 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_student_pin_code_student_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_type', models.CharField(choices=[('GUEST', 'Guest / Public Visitor'), ('PARENT', 'Parent'), ('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('ADMIN', 'Admin / Super Admin')], default='GUEST', max_length=20)),
                ('guest_name', models.CharField(blank=True, default='Guest Visitor', max_length=100)),
                ('topic_summary', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('GENERAL', 'General Inquiries'), ('CURRICULUM_INQUIRY', 'Curriculum & CBC/Cambridge'), ('PRICING_PAYMENT', 'Pricing & M-Pesa Payments'), ('STUDENT_PROGRESS', 'Student Activity & Progress'), ('LEGAL_HOMESCHOOLING', 'Legal & Registration Concierge'), ('TECHNICAL_HELP', 'Technical Support')], default='GENERAL', max_length=50)),
                ('is_meaningful', models.BooleanField(db_index=True, default=False, help_text='True if conversation contains real questions, ignoring basic hi/hello')),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive / Satisfied'), ('NEUTRAL', 'Neutral / Information Seeking'), ('NEEDS_ATTENTION', 'Needs Attention / Follow-up'), ('FEATURE_REQUEST', 'Improvement / Feature Request')], default='NEUTRAL', max_length=30)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to='core.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('BOT', 'SomaBot Assistant')], max_length=10)),
                ('text', models.TextField()),
                ('intent', models.CharField(blank=True, default='inquiry', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
